import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

const brainWaveLogo = '/assets/brainwave-symbol.svg'; // ******** 파비콘 이미지 가져옴
export const metadata: Metadata = {
    title: 'Brainwave', // ********************** 사이트 명 수정
    description: 'Generated by create next app',
    icons: {
        icon: brainWaveLogo, // *************** 파비콘 이미지 설정
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
